kedro-org/kedro-plugins

- kedro-telemetry/requirements.txt
- kedro-telemetry/tests/test_masking.py
_Related to https://github.com/kedro-org/kedro/pull/1260_
`kedro-telemetry` has had an explicit dependency on `click`, which means that if we were to update `click` version on `kedro` now, users wouldn't be able to install `kedro-telemetry` due to a dependency clash. Deleting this so that we rely on whatever `click` version `kedro` is using.
I believe this, including a fix for https://github.com/kedro-org/kedro/issues/1249, would be best included in an upcoming release so we're in a good position for 0.18.
_I tested to make sure `click==8.x` still works with telemetry._
Created new conda env where I `pip installed .` kedro from branch above and kedro-telemetry from this branch. Double-checked that `click` was newer version:
```
pip freeze | grep click
```
resulting in:
```
click==8.0.4 …
```
> [KED-3080] Remove click requirement

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_masking.py
- kedro-telemetry/tests/test_plugin.py
Two related GH issues:
https://github.com/kedro-org/kedro/issues/1289
https://github.com/kedro-org/kedro/issues/1249
Today - if consent provided, but the user has no access to the internet  an error is raised. This PR introduces a small exception handler that simply raises warnings whenever a `requests.exceptions.RequestException` base exception is raised.
> Fix connection error issue in telemetry

- .circleci/continue_config.yml
- kedro-telemetry/requirements.txt
- kedro-telemetry/setup.py
- kedro-telemetry/test_requirements.txt
- kedro-telemetry/tests/test_masking.py
First step to preparing `kedro-telemetry` for release when Kedro `0.18.0` is released. 
Temporarily pinned to use kedro from develop to make sure everything works. Will revert this and point to kedro 0.18.0 when it's released.
> Prepare `kedro-telemetry` for release

- .circleci/continue_config.yml
- kedro-docker/features/docker.feature
- kedro-docker/features/steps/cli_steps.py
- kedro-docker/kedro_docker/plugin.py
- kedro-docker/requirements.txt
- kedro-docker/setup.py
- kedro-docker/test_requirements.txt
Signed-off-by: Merel Theisen <merel.theisen@quantumblack.com>
First step to preparing `kedro-docker` for release when Kedro 0.18.0 is released.
> Prepare `kedro-docker` for release

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_masking.py
- kedro-telemetry/tests/test_plugin.py
Related issue: https://github.com/kedro-org/kedro-plugins/issues/11
When having no write access in a project, running any kedro command will raise an error with kedro-telemetry which then stops kedro from running everything. A broken kedro-telemetry shouldn't prevent users from using kedro.
> Prevent Telemetry breaking Kedro when no write permissions

- README.md
- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
Signed-off-by: noklam <nok.lam.chan@quantumblack.com>
> There's two problems with how kedro-telemetry does logging at the moment:
> 
> 1. [Sometimes it uses `click.secho`](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-telemetry/kedro_telemetry/plugin.py#L57) and [sometimes it uses logging](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-telemetry/kedro_telemetry/plugin.py#L64). This is inconsistent.
> 2. Due to changes in [Improve logging setup in Kedro [parent issue] kedro#1461](https://github.com/kedro-org/kedro/issues/1461), as it stands, no kedro-telemetry logging message that is < WARNING will display now.
> 
> For point 1, technically speaking I think both these message should use `logging.debug` (not info) rather than `click.echo`. Since by default these …
> Change some of the logging message to `DEBUG`  in `kedro-telemetry`

- kedro-airflow/README.md
- kedro-airflow/features/airflow.feature
The `pandas-iris` starter was simplified a while back, but we didn't update the tests for `kedro-airflow` that uses the starter.
> Update airflow tests to latests `pandas-iris`

- .circleci/continue_config.yml
Signed-off-by: Nok Chan <nok.lam.chan@quantumblack.com>
In the last PR #38, I made a silly mistake😅 during some merging process and delete the `continue_config.yml` completely without noticing, this PR will put back the CI to the last commit at https://github.com/kedro-org/kedro-plugins/blob/ad0755f503b275b73aeb8feb592a0ec0ea1bca8e/.circleci/continue_config.yml
> Revert CI config to lastest commit

- kedro-airflow/setup.py
See issue #53 
I have removed tests_require from setup.py
- [NA] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [NA] Updated the documentation to reflect the code changes
- [NA] Added a description of this change in the relevant `RELEASE.md` file
- [NA] Added tests to cover my changes
> Remove deprecated `tests_require` from `setup.py` in Kedro-Airflow

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/setup.py
- kedro-telemetry/tests/test_plugin.py
See #44, quotes related to the actual tasks related to the scope of this PR.
> To work out the size of a Kedro project, probably tracked per username:
- Number of datasets
- Number of nodes
- Number of pipelines
To work out how many team members are on a project, to show that Kedro helps with collaboration:
- Number of projects, identified by project_name
- A count of username per project
> **If possible add:** Size of projects by internal vs external users
> 
> **Nice to have:** Could we figure out what parts of a pipeline are data engineering vs data science specific?
> This issue was discussed as part of a **Technical Design** session:
> 
> * Size should be determined by the number of nodes in the default pipeline and the number of dataset entries in the catalog
> * Currently we use …
> Expand telemetry to better understand size of kedro projects in the wild

- kedro-datasets/pyproject.toml
- kedro-datasets/tests/pandas/test_csv_dataset.py
Signed-off-by: Jannic Holzer <jannic.holzer@quantumblack.com>
Resolves #67
Discovered that the source of the bug is another bug in moto (tested with moto==4.0.8, moto==3.0.4). Changing order of tests, so that TestCSVDataSetS3::test_load_and_confirm runs before TestCSVDataSet::test_protocol_usage avoids encountering the bug.
> Implement fix for failing test for loading CSVDataSet from S3 bucket

- kedro-datasets/kedro_datasets/pandas/parquet_dataset.py
- kedro-datasets/tests/pandas/test_parquet_dataset.py
Related issue: https://github.com/kedro-org/kedro-plugins/issues/88
Pandas now support the loading of parquet natively. It should be possible to remove the if-else statement here: https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/kedro_datasets/pandas/parquet_dataset.py#L161-L169
> Change `ParquetDataSet` to load using pandas instead of parquet

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Resolves #83.
Currently, when `kedro-telemetry` is installed in a packaged project that is deployed without a `pyproject.toml` file, a `RuntimeError` is thrown which prevents Kedro from being used at all in this way. It is currently necessary to read `pyproject.toml` to get three pieces of information about the project, which are then sent to heap:
- Package name
- Project name
- Project version
~~In the case that no `pyproject.toml` is present, I believe there is no other guaranteed 'source of truth' for these values. Therefore, my approach is to set these values to the string `undefined` in this case.~~
Instead of using `pyproject.toml` to find these values, this PR makes the following changes:
- Package name is found using the import `from kedro.framework.project import PACKAGE_NAME`. …
> Fix `kedro-telemetry` dependency breaking packaged projects without `pyproject.toml`

- kedro-datasets/kedro_datasets/video/video_dataset.py
The doc string had a syntax error, no space between `.. code-block:: yaml` and the start of the example, which makes the read the doc build fail. 
Ran the build locally to check it's working.
> Fix dataset docs

- kedro-datasets/kedro_datasets/tracking/metrics_dataset.py
The doc loooks to have an error in the example.
Incorrect:
```yaml
cars:
type: metrics.MetricsDataSet
filepath: data/09_tracking/cars.json
```
Correct:
```yaml
cars:
type: tracking.MetricsDataSet
filepath: data/09_tracking/cars.json
```
This is just for the doc. No modification on code.
> Fix an error in docstring of MetricsDataSet

- kedro-datasets/RELEASE.md
- kedro-datasets/setup.py
We only use PyArrow for `pandas.ParquetDataSet` as such I suggest we keep our versions pinned to the same range as [Pandas does](https://github.com/pandas-dev/pandas/blob/96fc51f5ec678394373e2c779ccff37ddb966e75/pyproject.toml#L100) for the same reason.
As such I suggest we remove the upper bound as we have users requesting later versions in [support channels](https://kedro-org.slack.com/archives/C03RKP2LW64/p1674040509133529)
Tweaked boundaries
> Bump relax pyarrow version to work the same way as Pandas

- .circleci/continue_config.yml
Signed-off-by: Merel Theisen <merel.theisen@quantumblack.com>
The setup for running `kedro-dataset` in other plugin workflows wasn't set up correctly. This was discovered in this PR: https://github.com/kedro-org/kedro-plugins/pull/99
To check whether the `kedro-datasets` test should be run or not the check should look at `<<parameters.plugin>>` and not at `<<pipeline.parameters.run-build-kedro-datasets>>`. This is because when changes are made in both `kedro-datasets` and another plugin, `<<pipeline.parameters.run-build-kedro-datasets>>` would be set to true for all builds, and thus all plugin builds would end up running `kedro-datasets` tests which is not what should happen. 
I tested the change by branching of https://github.com/kedro-org/kedro-plugins/pull/99 with …
> Change check to check on plugin name

- kedro-airflow/.coveragerc
- kedro-airflow/pyproject.toml
Signed-off-by: Merel Theisen <merel.theisen@quantumblack.com>
Coverage was setup incorrectly and flagging lines in test files as not being covered. See https://app.circleci.com/pipelines/github/kedro-org/kedro-plugins/747/workflows/aef169d9-d389-4a08-9572-89f3e9f12125/jobs/8429
Moved the settings for coverage checking to `pyproject.toml` just like we have it in the core kedro repo.
> [kedro-airflow] Move coverage settings to pyproject.toml

- kedro-docker/.coveragerc
- kedro-docker/pyproject.toml
Signed-off-by: Merel Theisen <merel.theisen@quantumblack.com>
Make the coverage settings consistent with the other plugins. Same as: https://github.com/kedro-org/kedro-plugins/pull/105
> [kedro-docker] Move coverage settings to pyproject.toml

- kedro-datasets/kedro_datasets/pickle/pickle_dataset.py
- kedro-datasets/kedro_datasets/redis/redis_dataset.py
Two outdated URLs are causing kedro CI builds to fail on `linkcheck`, this change should fix it.
> Fix outdated links in Kedro Datasets

- kedro-datasets/kedro_datasets/api/api_dataset.py
- kedro-datasets/kedro_datasets/dask/parquet_dataset.py
- kedro-datasets/kedro_datasets/json/json_dataset.py
- kedro-datasets/kedro_datasets/matplotlib/matplotlib_writer.py
- kedro-datasets/kedro_datasets/pandas/csv_dataset.py
- kedro-datasets/kedro_datasets/pandas/excel_dataset.py
- kedro-datasets/kedro_datasets/pandas/feather_dataset.py
- kedro-datasets/kedro_datasets/pandas/gbq_dataset.py
- kedro-datasets/kedro_datasets/pandas/generic_dataset.py
- kedro-datasets/kedro_datasets/pandas/hdf_dataset.py
- kedro-datasets/kedro_datasets/pandas/json_dataset.py
- kedro-datasets/kedro_datasets/pandas/parquet_dataset.py
- kedro-datasets/kedro_datasets/pandas/sql_dataset.py
- kedro-datasets/kedro_datasets/pandas/xml_dataset.py
- kedro-datasets/kedro_datasets/pickle/pickle_dataset.py
- kedro-datasets/kedro_datasets/pillow/image_dataset.py
- kedro-datasets/kedro_datasets/plotly/json_dataset.py
- kedro-datasets/kedro_datasets/plotly/plotly_dataset.py
- kedro-datasets/kedro_datasets/redis/redis_dataset.py
- kedro-datasets/kedro_datasets/spark/deltatable_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_hive_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_jdbc_dataset.py
- kedro-datasets/kedro_datasets/svmlight/svmlight_dataset.py
- kedro-datasets/kedro_datasets/tensorflow/tensorflow_model_dataset.py
- kedro-datasets/kedro_datasets/text/text_dataset.py
- kedro-datasets/kedro_datasets/tracking/json_dataset.py
- kedro-datasets/kedro_datasets/tracking/metrics_dataset.py
- kedro-datasets/kedro_datasets/video/video_dataset.py
- kedro-datasets/kedro_datasets/yaml/yaml_dataset.py
Apply changes from https://github.com/kedro-org/kedro/pull/2181.
* Created a patch using `git format-patch -1 e598bfc8ac0a6aa30b4c6c468b0c1300fa3142d6`
* Modified the paths
* Applied changes using `patch -p1 < ../kedro/0001-Fix-docs-formatting-and-phrasing-for-some-datasets-2.patch`
* `git patch` wasn't successful except on like 3 files, and I couldn't figure out what was different about the paths 🤷 
* Manually applied changes to 3 files that had indentation changes, where `patch` failed
> Fix docs formatting and phrasing for some datasets

- kedro-airflow/kedro_airflow/__init__.py
- kedro-airflow/tests/conftest.py
- kedro-docker/kedro_docker/__init__.py
- kedro-telemetry/kedro_telemetry/__init__.py
- kedro-telemetry/tests/test_masking.py
- kedro-telemetry/tests/test_plugin.py
Fix broken tests resulting from https://github.com/kedro-org/kedro/pull/2219
Triggered tests for all plugins (except datasets, but manually checked that tests don't require metadata there). Standardized docstrings along the way. 🤷
> Pass the `kedro_init_version` to `ProjectMetadata`

- kedro-airflow/kedro_airflow/plugin.py
See
https://github.com/kedro-org/kedro/issues/1749
As plugin docstring end up showing in the kedro CLI, the easier solution is to remove the docstring.
> Keep Kedro-Airflow plugin docstring from appearing in `kedro -h`

- tools/circleci/circleci_release.py
- tools/circleci/github_release.py
- tools/circleci/utils/check_no_version_pypi.py
Bandit security checks were failing with bandit `1.7.5`
Adding timeout to `requests.post()` calls fixed it. I ran the checks locally to verify.
> Fix bandit checks by adding timeout to `requests.post()` calls

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/spark/spark_dataset.py
- kedro-datasets/tests/spark/test_spark_dataset.py
Signed-off-by: Nok Chan <nok.lam.chan@quantumblack.com>
Close https://github.com/kedro-org/kedro-plugins/issues/117
The final decision is to just update the doc and add support for `fsspec.filesystem` since the `DatabricksFileSystem` isn't useful for the Spark usecase.
> To summarise the current issue:
> 
> ## Summary
> 1. When `dbfs/` not include in path:❌
> 
> * Spark will always add `dbfs/` prefix - see https://docs.databricks.com/files/index.html#understand-default-locations-with-examples
> * `_fetch_latest_version` will use `os` library, by default it doesn't use the `dbfs` as root - as a result it can't find the file because Spark saved it in `dbfs/filepath` but `os` is looking in `filepath`
> 
> This is why when `versioned: True` + `dbfs/` not used in the filepath it cannot load …
> Update SparkDataSet's doc and add support for `fsspec`

- kedro-datasets/kedro_datasets/snowflake/snowpark_dataset.py
See errors at https://github.com/kedro-org/kedro/pull/2485.
I tried a docs build locally:
```diff
diff --git a/docs/kedro-datasets-docs.sh b/docs/kedro-datasets-docs.sh
index 10054034..aa4bc8f7 100755
--- a/docs/kedro-datasets-docs.sh
+++ b/docs/kedro-datasets-docs.sh
@@ -7,7 +7,7 @@ set -o nounset
set -o errexit
-pip install kedro-datasets
-pip install --no-deps -t kedro/to_delete kedro-datasets
+pip install ../kedro-plugins/kedro-datasets
+pip install --no-deps -t kedro/to_delete ../kedro-plugins/kedro-datasets
mv kedro/to_delete/kedro_datasets kedro/datasets
rm -r kedro/to_delete
```
And then `make build-docs`.
Without the change, it fails:
```
/home/docs/checkouts/readthedocs.org/user_builds/kedro/checkouts/2485/kedro/datasets/snowflake/snowpark_dataset.py:docstring of …
```
> Fix SnowparkTableDataSet docstrings

- kedro-datasets/RELEASE.md
- kedro-datasets/setup.py
It's an oversight that we didn't sync the requirements properly for `delta-spark`. See https://github.com/kedro-org/kedro/commit/27f5490893dfce10a63ddeb57bf45110587d2b90
> Sync delta-spark requirements

- tools/circleci/circleci_release.py
#43 implement the Auto Release process, so we don't have to manually publish plugins. Recently, there are some release CI fails silently, [the CI shows green even those the request didn't went through](https://app.circleci.com/pipelines/github/kedro-org/kedro-plugins/997/workflows/19909855-36ea-4792-a99a-8251c3abe534/jobs/11212)
Update the script to use `sys.exit(1)` when the request response is unexpected.
> Update Release to fail when release isn't triggered properly

- .gitpod.yml
Currently opening gitpod will installed a Python 3.11 which breaks everything because we don't support it set. This PR introduce a simple .gitpod.yml to get it started.
> Introdcuing .gitpod.yml to kedro-plugins

- .github/workflows/check-plugin.yml
- kedro-datasets/test_requirements.txt
Bumping the version of `pytables` from 3.6 to 3.7 allows it to be installed on windows system for higher versions (>3.9) of Python and we can remove the extra conditional step of installing `tables` separately for `windows` in the GitHub Actions `unit-test` job for `kedro-datasets`.
> [kedro-datasets] Bump version of `tables` in `test_requirements.txt` 

- .github/workflows/validate-pr-title.yaml
[...]
- It's not clear which changes affect which plugins
- Denoted inconsistently using tags like `[kedro-docker]` on PR/issues (nonstandard solution)
[...]
_Originally posted by @deepyaman in https://github.com/kedro-org/kedro/issues/2333#issuecomment-1434492921_
Tested manually. Also, have used the Action on other projects previously. The configuration is pretty much that documented in the Action's repo.
Can somebody with rights ensure that the squash-merge strategy IS NOT set to use the commit message if there's only one commit? See https://github.com/amannn/action-semantic-pull-request#installation.
Is there (going to be) a CONTRIBUTING.md for this repo? If so, we can include the following:
The Kedro-Plugins repository requires that you [squash and merge your pull request …
> ci: ensure title matches Conventional Commits spec

- .circleci/continue_config.yml
- .github/workflows/check-plugin.yml
- .github/workflows/kedro-airflow.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/kedro-docker.yml
- .github/workflows/kedro-telemetry.yml
- kedro-datasets/pyproject.toml
- kedro-docker/pyproject.toml
- kedro-telemetry/pyproject.toml
Closes #193
Closes #194 (duplicate)
> ci: ensure plugin requirements get installed in CI

- .github/workflows/kedro-airflow.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/kedro-docker.yml
- .github/workflows/kedro-telemetry.yml
If you see a PR like #189, you'll see jobs are being run on `push` and `pull_request` (instead of either-or).
Furthermore, the path filtering is a bit too aggressive, in that it won't consider changes to files like `.pre-commit-config.yaml`, etc. It may be a bit too conservative now, in that a change to `kedro-airflow.yaml` will trigger all the checks, but:
1. changing CI workflows is comparatively rare
2. ignoring folders is easier than including the plugin folder + an exhaustive list of files
Maybe we can just add the CI workflow definitions to `paths-ignore` as well.
> ci: don't run checks on both `push`/`pull_request`

- .github/workflows/merge-gatekeeper.yml
To make this work, it requires change of branch setting and add "Status Check" for `merge-gatekeeper`
> ci: Create merge-gatekeeper.yml to make sure PR only merged when all tests checked.

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release datasets version 1.3.0
> feat: Release `kedro-datasets` version `1.3.0`

- kedro-datasets/tests/tensorflow/test_tensorflow_model_dataset.py
Luckily happens that `MagicMock`s are falsy, but this is a clear mistake.
> fix(datasets): use `side_effect`, not `side_effct`

- .github/workflows/check-plugin.yml
- .github/workflows/validate-pr-title.yaml
- kedro-datasets/kedro_datasets/geopandas/__init__.py
- kedro-datasets/tests/databricks/test_managed_table_dataset.py
- kedro-datasets/tests/email/test_message_dataset.py
- kedro-datasets/tests/geojson/test_geojson_dataset.py
- kedro-datasets/tests/holoviews/test_holoviews_writer.py
- kedro-datasets/tests/json/test_json_dataset.py
- kedro-datasets/tests/libsvm/test_svmlight_dataset.py
- kedro-datasets/tests/matplotlib/test_matplotlib_writer.py
- kedro-datasets/tests/pandas/test_csv_dataset.py
- kedro-datasets/tests/pandas/test_excel_dataset.py
- kedro-datasets/tests/pandas/test_feather_dataset.py
- kedro-datasets/tests/pandas/test_hdf_dataset.py
- kedro-datasets/tests/pandas/test_json_dataset.py
- kedro-datasets/tests/pandas/test_parquet_dataset.py
- kedro-datasets/tests/pandas/test_xml_dataset.py
- kedro-datasets/tests/pickle/test_pickle_dataset.py
- kedro-datasets/tests/pillow/test_image_dataset.py
- kedro-datasets/tests/polars/test_csv_dataset.py
- kedro-datasets/tests/spark/test_memory_dataset.py
- kedro-datasets/tests/tensorflow/test_tensorflow_model_dataset.py
- kedro-datasets/tests/text/test_text_dataset.py
- kedro-datasets/tests/tracking/test_json_dataset.py
- kedro-datasets/tests/tracking/test_metrics_dataset.py
- kedro-datasets/tests/yaml/test_yaml_dataset.py
In réponse to kedro-org/kedro#2500 changing the error message, any tests that specifically check that message need to be updated accordingly.
Note that this will no pass until kedro-org/kedro#2673 is merged. #239 showcases a passing build (hardcoded to build using the `refactor/rename-data-sets` branch of #2673).
* Update the "no versioning" error message
* Other trivial cleanup (remove useless suppression, etc.)
> test(datasets): update the "no versioning" message

- kedro-airflow/README.md
Document how to use alternative Airflow Operators. `kedro-airflow` should not support all operators in the current situation: apart from there being too many to keep track of, this would introduce unnecessary maintenance burden.
Being explicit about the non-goals of a project is better than leave it undocumented. 
Note that these instructions remain valid if the template would be written using the [TaskFlow](https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html#using-the-taskflow-api-with-complex-conflicting-python-dependencies) syntax as proposed in https://github.com/kedro-org/kedro-plugins/issues/25.
Open for discussion of course.
Closes https://github.com/kedro-org/kedro-plugins/issues/27
> docs: Instructions on custom Airflow Operators

- .github/workflows/kedro-airflow.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/kedro-docker.yml
- .github/workflows/kedro-telemetry.yml
related to: https://github.com/kedro-org/kedro/issues/2335
The CI on kedro-plugins is not run regularly - for the core Kedro repo we have frequent changes so any dependency changes will be found out pretty quickly. For plugins, there could be a dependency change but we only have new commits after a few months. In this case, it is unclear whether the new changes break the CI or something in between happened, often it takes a long time to isolate the error.
Added cron jobs to CI.
> chore: Add nightly build

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Patch release that fixes the bad docstring in the `DeltaTableDataSet`
> build(datasets): Release 1.5.1

- kedro-datasets/pyproject.toml
#263 modified optional-dependencies in pyproject.toml, leading to issues with dependency loading for `spark` when running `kedro-datasets[spark.SparkDataSet, pandas.ParquetDataSet]` (as seen in the iris-databricks starter). This PR corrects the pyproject.toml syntax to resolve the issue.
Tested manually using the iris-databricks starter only.
> fix(datasets): Correct pyproject.toml syntax for optional dependencies

- kedro-datasets/README.md
I was checking out the repo and found a broken link to the root of the datasets docs.
> docs: Fix broken link to datasets docs in README.md

- kedro-datasets/pyproject.toml
- kedro-datasets/setup.py
This PR transfers optional dependencies from `pyproject.toml` back to `setup.py`.
The naming conventions for `kedro-datasets` extras do not adhere to Python packaging standards. This misalignment leads to issues with nesting in `pyproject.toml` optional dependencies. Our solution is two-steps:
- In the first step, we'll revert the optional dependencies back to `setup.py`.
- In the second step, we'll modify the naming syntax in the breaking release 2.0.0, coinciding with the release of kedro 0.19.
Manually tested: works well with .[all] and .[spark.SparkDataSet].
> fix(datasets): Revert the optional dependencies back to setup.py

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release 1.5.3
- This should be the last 1.5.x series for bug fix. Note this is important because from 1.5.0 -> 1.5.2 we suffer from different problems of optional dependencies, we want to ensure people can still upgrade painlessly (relatively) if they have pin `kedro-datasets~=1.5.0`. 
- Upcoming release should be 1.6.0 (Python 3.11 support)
- Change ManagedTableDataSet default to read-only, with options to overwrite.
- Revert optional dependencies to `setup.py`, since setuptools does not support pyproject.toml fully.
> build(datasets): Release/kedro datasets 1.5.3

- kedro-airflow/pyproject.toml
Fix #295 failing end to end tests for `kedro-airflow`  
There was a [new release for `apache-airflow` on 18th August 2023](https://airflow.apache.org/announcements/#august-18-2023) which broke something with `sqlalchemy`
What do we think about setting version for `apache-airflow` to `<2.7.0` for now?
> ci(airflow): Pin apache-airflow version

- kedro-datasets/RELEASE.md
- kedro-datasets/docs/source/kedro_datasets.rst
- kedro-datasets/kedro_datasets/__init__.py
- kedro-datasets/kedro_datasets/polars/generic_dataset.py
- kedro-datasets/setup.py
Release `kedro-datasets` 1.7.0
> build(datasets): Release `kedro-datasets` 1.7.0

- .github/workflows/kedro-telemetry.yml
- kedro-telemetry/RELEASE.md
- kedro-telemetry/tests/test_masking.py
Partial solution for #265
NOTE: linter's still running on python 3.8 because of some `pre-commit` errors. To be done as a follow up for all plugins. #331
> build(telemetry): Add python 3.11 to telemetry

- .github/workflows/nightly-build.yml
I noticed that the datasets tests were failing for a day or two but no issue was created. 
The if conditions on the success/failure of github actions jobs works weirdly. If one of the sub tasks fails the jobs for other python versions and os are cancelled so sometimes it skips the notification creation step. 
The status for the failed nightly build is shown as cancelled instead -> https://github.com/kedro-org/kedro-plugins/actions/workflows/nightly-build.yml
Tested on fork -
With `if: failure()` condition - https://github.com/ankatiyar/kedro-plugins/actions/runs/6184855180
With `if: ${{ !success() }}` condition - https://github.com/ankatiyar/kedro-plugins/actions/runs/6184875778
> ci: Update condition for creating a notification for nightly build failure

- kedro-datasets/tests/tensorflow/test_tensorflow_model_dataset.py
Tests are flaky; they pass if you run them enough times.
https://kedro-org.slack.com/archives/C054U0LJLAC/p1696272611234859?thread_ts=1693846107.068859&cid=C054U0LJLAC
> test(datasets): skip `tensorflow` tests on Windows

- kedro-airflow/features/steps/cli_steps.py
- kedro-datasets/setup.py
Resolve #369 
Same as on kedro https://github.com/kedro-org/kedro/pull/3126
New release of `pytables` which drops support for python 3.8 is causing this. 
* Pin `tables` version on `kedro-datasets` for python < 3.8
* ~~`kedro-airflow` e2e test uses `pandas-iris` starter but was downloading requirements for `kedro-datasets[PANDAS]` which includes the HDFdataset which relies on `tables` but `pandas-iris` just has a `CSVDataset` so updated this.~~ 
Some weird kubernetes related failure on `kedro-airflow` will fix as a follow up
> ci: Pin `tables` version

- kedro-datasets/kedro_datasets/pickle/pickle_dataset.py
- kedro-datasets/kedro_datasets/redis/redis_dataset.py
https://github.com/kedro-org/kedro-plugins/pull/361 introduced a link to github which causes the secret scan to fail. 
Fixed it by updating the link to point to the `master` branch of the linked repo.
> fix(datasets): Fix secret scan entropy error

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/spark/spark_dataset.py
- kedro-datasets/tests/spark/test_spark_dataset.py
Fix for #319 
I've implemented the fix for `s3`, `s3a`, `s3n`. If there's protocols I should add for Azure, GCP or others, let me know - I don't have experience with these and couldn't find the protocols to use, if they exist.
> fix(datasets): Don't warn for SparkDataset on Databricks when using s3

- .github/workflows/kedro-datasets.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- Makefile
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/spark/test_spark_hive_dataset.py
CI failures due to problematic `pip` version
Should be reverted when a new pip version is released. Mentioned in https://github.com/kedro-org/kedro/issues/3184
> chore: Pin pip version temporarily

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
- kedro-datasets/tests/polars/test_lazy_polars_dataset.py
Non-breaking release for Kedro Datasets.
Resolves #388
> build(datasets): Release `1.8.0`

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/tensorflow/tensorflow_model_dataset.py
when a model is saved in the TensorFlow SavedModel format ("tf" default option in tf.save_model when using TF 2.x) via the catalog.xml file, the subsequent loading of that model for further use in a subsequent node fails. The issue is linked to the fact that the model files don't get copied into the temporary folder, presumably because the _fs.get function "thinks" that the provided path is a file and not a folder.
Adding an terminating "/" to the path fixes the issue. This has been tested with the following catalog.yml entry to validate that the fix works:
"model_trained_experiment0":
type: tensorflow.TensorFlowModelDataset
filepath: data/06_models/experiment0/model/
This together with a pipeline made of a node outputting "model_trained_experiment0" and a subsequent node inputting …
> fix: TF model load failure when model is saved as a TensorFlow Saved Model format

- kedro-datasets/README.md
- kedro-datasets/RELEASE.md
- kedro-datasets/pyproject.toml
- kedro-datasets/setup.py
Drops support for Python 3.7 on `kedro-datasets`. Part of https://github.com/kedro-org/kedro/issues/2158.
> chore: Drop support for Python 3.7 on kedro-datasets

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
This PR fixes #382 by moving the sending of the heap to the `after_catalog_created` hook instead of the `after_context_created` hook. This prevents the creation of the catalog twice and thus double execution of `after_catalog_created` hooks as part of any downstream project.
> fix(telemetry): remove double execution by moving to after catalog created hook

- kedro-airflow/README.md
- kedro-airflow/pyproject.toml
- kedro-datasets/README.md
- kedro-docker/README.md
- kedro-telemetry/README.md
Closed #404 
- Added the python version policy to the `README.md` files of each plugin
- Added licence/contributing info to plugins where it was missing.
> docs: Add python version support policy to plugin `README.md`s

- Makefile
- kedro-datasets/MANIFEST.in
- kedro-datasets/kedro_datasets/conftest.py
- kedro-datasets/kedro_datasets/dask/parquet_dataset.py
- kedro-datasets/pyproject.toml
Partially addresses https://github.com/kedro-org/kedro/issues/2287
Also added a `tmp_path` fixture for doctests; existing tests should probably also use this, to prevent polluting devs' directories.
> test(datasets): fix `dask.ParquetDataset` doctests

- kedro-datasets/kedro_datasets/spark/README.md
Also, fix list formatting
As Jo mentioned, there are probably Pyspark instances in other repos than core
> chore(datasets): replace "Pyspark" with "PySpark"

- Makefile
- kedro-datasets/kedro_datasets/pandas/generic_dataset.py
Part of https://github.com/kedro-org/kedro/issues/2287
In `pandas.CSVDataset` the save_args are set by default to `DEFAULT_SAVE_ARGS: Dict[str, Any] = {"index": False}` in `pandas.GenericDataset` they're not so the index was being saved in the example leading to the expected and real result not matching.
> chore(datasets): Fix `pandas.GenericDataset` doctest

- Makefile
- kedro-datasets/kedro_datasets/pandas/generic_dataset.py
- kedro-datasets/kedro_datasets/partitions/incremental_dataset.py
- kedro-datasets/kedro_datasets/pillow/image_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_jdbc_dataset.py
- kedro-datasets/kedro_datasets/video/video_dataset.py
Part of [Make sure all example code blocks for datasets are runnable#2287](https://github.com/kedro-org/kedro/issues/2287)
- The "fix" for `IncrementalDataset` maybe isn't really a fix, but rather changing the example to not use S3. I think it's fine, but would like to hear what others think. **Edit: reverted these changes now because it didn't fix the issue.**
- Fixed the import of `spark.SparkJDBCDataset`, but it needs more changes to work. 
- Fixed the `pillow.ImageDataset` and `video.VideoDataset` by linking to sample video and image data.
> chore(datasets): Fix more doctest issues 

- kedro-datasets/kedro_datasets/conftest.py
When I copy-pasted the example from pytest docs, I forgot to change `add_np` to something else. Oops.
No actual effect, but `add_np` doesn't make sense.
> chore(datasets): fix accidental reference to NumPy

- Makefile
- kedro-datasets/kedro_datasets/pandas/sql_dataset.py
> test(datasets): make SQL dataset examples runnable

- kedro-datasets/README.md
> docs(datasets): Fix broken links in README

- kedro-datasets/kedro_datasets/partitions/partitioned_dataset.py
A user was facing problems trying to use the `PartitionedDataset` because the import has changed now the dataset has moved to `kedro-datasets`: https://github.com/kedro-org/kedro-plugins/issues/501
Updated docstring to new import path.
> chore(datasets): Update partitioned dataset docstring

- kedro-airflow/features/airflow.feature
- kedro-airflow/features/steps/cli_steps.py
- kedro-airflow/pyproject.toml
Fix #315 
- Unpin `apache-airflow` in test requirements
- Changed the starter used in e2e tests to `spaceflights-pandas` to `astro-airflow-iris`
This is because `apache-airflow` has moved to `pydantic v2` in 2.8.0. The spaceflights starters have `kedro-viz` in their requirements and `kedro-viz` still uses `pydantic v1`. So, in the e2e-tests, the installation of the kedro project, which also installs `kedro-viz` was downgrading pydantic to v1 which was causing failures. `astro-airflow-iris` doesn't have `kedro-viz` in the requirements.
> chore(airflow): Bump `apache-airflow` version

- kedro-datasets/kedro_datasets/dask/parquet_dataset.py
- kedro-datasets/setup.py
Fix https://github.com/kedro-org/kedro-plugins/issues/520
I think the tests on `kedro-datasets` were failing because there was a new release of `pyarrow` recently. The `dask` version was pinned to a 2021 version for a while. I've bumped the dask version in the test requirements and changed the code snippet in the doc string to get the doc test running.
> ci(datasets): Unpin dask

- kedro-airflow/README.md
- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/airflow_dag_template.j2
- kedro-airflow/kedro_airflow/grouping.py
- kedro-airflow/kedro_airflow/plugin.py
- kedro-airflow/pyproject.toml
- kedro-airflow/tests/test_node_grouping.py
- kedro-airflow/tests/test_plugin.py
When running Kedro nodes using Airflow, MemoryDataSets are often not shared across operators. This will cause the DAG run to fail. 
MemoryDataSets may be used to provide logical separation between nodes in Kedro, without the overhead of needing to write to disk (and in the case of distributed running needing multiple executors).
This PR adds an option to group all nodes that are connected through MemoryDataSets together. This preserves the option to have logical separation in Kedro, with little computational overhead.
(Previously raised in [kedro-k8s-airflow](https://github.com/getindata/kedro-airflow-k8s/issues/138))
Built on top of https://github.com/kedro-org/kedro-plugins/pull/233, as we use the Kedro session. I can make them independent if there are blockers for that PR.
> feat: `kedro-airflow` group in memory nodes

- kedro-datasets/pyproject.toml
kedro-datasets 2.0 requires `AbstractDataset` which is not compatible with kedro < 0.19. This should reflect in the pyproject.toml
> ci(datasets): Update pyproject.toml to pin Kedro 0.19 for kedro-datasets

- kedro-datasets/setup.py
- kedro-datasets/tests/pandas/test_deltatable_dataset.py
Related to: https://github.com/kedro-org/kedro-plugins/issues/540
The latest release of `deltalake 0.15.2` broke one our tests after digging into their [changes](https://github.com/delta-io/delta-rs/releases/tag/python-v0.15.2), I believe some changes in their Rust code has altered the way data is appended and retrieved from the Delta table which is causing different order of rows in the DataFrame. If we aren't to fussed about the ordering I added sorting before comparing the DataFrames in our tests.
Added sorting to the DF before comparison.
> fix(datasets): Debug and fix `kedro-datasets` nightly build failures

- kedro-datasets/setup.py
- kedro-datasets/tests/pandas/test_deltatable_dataset.py
Fix Snowflake dataset cannot installed with latest pyarrow 14.0.1 #453 
I believe the contraint was put there when snowpark was not available for python 3.11. Nor snowpark nor the dataset needs pyarrow as dependency.
> fix(datasets): Drop pyarrow constraint when using snowpark

- .github/workflows/check-release.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
Bump actions to versions that use node 20 instead of node 16, which have been deprecated.
> chore: bump actions versions

- kedro-telemetry/kedro_telemetry/masking.py
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_masking.py
This PR modifies the algorithm for masking CLI inputs:
1. It retains the initial segment of the command, permitting only commands from the Kedro CLI, up until the point where parameter sections start.
2. It masks all inputs except for the permitted parameter keywords specific to that Kedro CLI command.
Additionally, the sequence of operations in KedroTelemetryCLIHooks has been altered: we now first check for the user's consent. If it has not been provided, we take no further action. Previously, we would parse the Kedro CLI structure first, which consumed time unnecessarily.
> fix: kedro-telemetry masking

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Closes #483 
This implementation diverges from the Dagster in several ways:
* `KNOWN_CI_ENV_VAR_KEYS` is implemented as a list, not a set, as lists have better iteration time on average
* We use `os.getenv()` instead of `os.environ.get()` for consistency within our codebase
* `KNOWN_CI_ENV_VAR_KEYS` does not contain keys for tools that set the CI env in our implementation, all keys exempted belong to tools that would otherwise set the CI env var to true
> feat(telemetry): Add is_ci_env environment to reported project telemetry

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/pandas/sql_dataset.py
- kedro-datasets/tests/pandas/test_sql_dataset.py
This PR adds the feature to allow additional parameters for sqlalchemy engine when using a sql dataset.
This is for example necessary when you want to set the pool size of the connection or add additional authentication arguments.
Examples in a credentials.yaml are:
```
db_credentials:
con: postgresql://scott:tiger@localhost/test
pool_size: 10 # additional parameters
hive_credentials:
con: hive://user@server:10000/default
connect_args:
auth: 'KERBEROS'
kerberos_service_name: 'hive'
```
> feat(datasets): allow additional parameters for sqlalchemy engine when using sql dataset

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
> build(telemetry): Release 0.3.2

- kedro-docker/features/docker.feature
Fix #558 
The failures are not related to `kedro-docker` itself but an incompatibility between the latest release of `scikit-learn` and `ParallelRunner`. Ticket to fix the underlying issue - https://github.com/kedro-org/kedro/issues/3674
In the meanwhile, we can just skip running the `data_science` pipeline with the `ParallelRunner` in the e2e test for `kedro-docker` to unblock the CI and then revert this after https://github.com/kedro-org/kedro/issues/3674 is fixed.
> ci(docker): Only run one pipeline with the `ParallelRunner` in the e2e test

- kedro-datasets/pyproject.toml
> build(datasets): fix typos in definition of extras

- MagicMock/user_config_dir()/140095031570448/telemetry.conf
- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/pyproject.toml
- kedro-telemetry/tests/test_plugin.py
This PR introduces a unique identifier (UUID) for each user of the kedro-telemetry.
- Instead of relying on hashed usernames, we now generate a unique UUID for each user. This UUID is generated using uuid.uuid4() function.
- Generated UUID is stored in a user-specific configuration file, leveraging the appdirs library to determine the appropriate OS-specific path for this file (~/Library/Application Support/kedro/telemetry.conf on MAC)
- If a UUID does not already exist, the function generates a new one, stores it, and then uses this UUID in subsequent telemetry events.
> feat(telemetry): Unique User IDs in kedro-telemetry - merge only for kedro-telemetry release 0.4.0

- .github/workflows/e2e-tests.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/kedro-telemetry.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- kedro-datasets/.readthedocs.yaml
- kedro-telemetry/RELEASE.md
Related #613, Also solve https://github.com/kedro-org/kedro-plugins/issues/618
No changes required to upgrade to Python 3.12 as such for `kedro-telemetry`
> build(telemetry): Add python 3.12 support

- kedro-airflow/kedro_airflow/plugin.py
- kedro-airflow/tests/conftest.py
- kedro-airflow/tests/test_plugin.py
This PR introduces an option to use the `--tags="ABC"` argument together with the `airflow create` command, enabling the filtering of nodes based on specific tags.
> feat(airflow): add --tags option for node filtering in airflow create

- kedro-airflow/kedro_airflow/plugin.py
- kedro-airflow/tests/conftest.py
- kedro-airflow/tests/test_plugin.py
Following the discussion wrt https://github.com/kedro-org/kedro/pull/3683
- Remove `bootstrap_project` and get `project_path` from `metadata`
- Update tests
-
> refactor(airflow): Remove `bootstrap_project`

- kedro-telemetry/tests/test_masking.py
Adds the `--telemetry` flag to the `test_get_cli_structure_depth` on kedro-telemetry, to account for the same changes done on the main Kedro repository.
> fix: Add `--telemetry` flag to to kedro-telemetry CLI masking tests.

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/ibis/__init__.py
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/ibis/test_table_dataset.py
Officially add Ibis `TableDataset` introduced in https://kedro.org/blog/building-scalable-data-pipelines-with-kedro-and-ibis.
> feat(datasets): add dataset to load/save with Ibis

- kedro-datasets/CONTRIBUTING.md
- kedro-datasets/experimental/README.md
Resolves #579 
FYI: I've asked for review from a longer list than usual, because this introduces a new contribution model to datasets and I think most people in the TSC should know about that. 
- Added a section on the difference between regular and experimental datasets
- Added a section on the graduation process from experimental to regular
- Added a section on the demotion process from regular to experimental
- Updated the dataset contribution process to include mention of where to add the new dataset and mention review by the TSC
> docs: Add description of experimental and regular datasets to contribution guide

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
Release `kedro-telemetry 0.4.0`
> build(telemetry): Release 0.4.0

- kedro-airflow/README.md
The Kedro Airflow Deployment manual was recently updated via two pull requests: [#3792](https://github.com/kedro-org/kedro/pull/3792) and [#3860](https://github.com/kedro-org/kedro/pull/3860). That PR will fix the link in the `README.md` of `kedro-airflow` to point to the correct deployment manual.
> fix(airflow): fix the link to correct deployment manual

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
FIX #507 
Related docs update https://github.com/kedro-org/kedro/pull/3897
Manually tested the following scenario:
1. Created a project with consent
- `project id` does not exist - it is generated and saved in `pyproject.toml`
- `project id` exists - it is loaded from `pyproject.toml`, joined with the `package name`, hashed and used
- package name changes,  `project id` exists - it is loaded from `pyproject.toml`, joined with the new `package name`, hashed and used
2. Created a project without consent
- project id is not created
3. Packaging project
- package kedro project with modified `pyproject.toml` - works without errors
- run packaged project with consent=True and existing `pyproject.toml` - `project id` is generated and saved in `pyproject.toml`
- run packaged project with …
> fix(telemetry): Single project identifier

- kedro-datasets/tests/pandas/test_deltatable_dataset.py
Fix https://github.com/kedro-org/kedro-plugins/issues/719
Reason - https://github.com/delta-io/delta-rs/commit/dc10adabf7b162f50ce19310f64d8fdff527fbba
> fix(datasets): Update deprecated parameter in `pandas.DeltaTableDataset` test

- kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
- kedro-datasets/kedro_datasets/huggingface/hugging_face_dataset.py
- kedro-datasets/kedro_datasets/huggingface/transformer_pipeline_dataset.py
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/kedro_datasets/polars/eager_polars_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_streaming_dataset.py
Fix issue: #699 
- added `metadata` to `__init__` of some datasets
> fix(datasets): add metadata parameter to datasets

- kedro-datasets/pyproject.toml
Fix #740 temporarily
Copied from https://github.com/kedro-org/kedro-plugins/pull/750#issuecomment-2210458062
The docs test failure is because of some shenanigans with fsspec in #750.
It's a bug in datasets version<2.15. The unpinning of gcsfs brings the fsspec version up to date but the later versions of datasets is not compatible with later versions of fsspec. They merged support a few days ago https://github.com/huggingface/datasets/pull/7017 but not released yet. 
I think gcsfs will be okay to unpin when the release is out but we can pin accelerate for now and unblock the CI - https://github.com/kedro-org/kedro-plugins/pull/751
In our CI we run on an older version of
> ci(datasets): pin `accelerate`

- kedro-datasets/pyproject.toml
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Partly solves https://github.com/kedro-org/kedro-plugins/issues/726
- `_confirm_consent` was removed
- now we use consent from the `.telemetry` file if it exists and has a valid format otherwise, we consider consent is `True`
> feat(telemetry): Remove consent confirmation prompt for `kedro-telemetry`

- .github/workflows/e2e-tests.yml
- .github/workflows/kedro-datasets.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
> ci: Upgrade `uv` to avoid timeouts

- kedro-telemetry/tests/test_masking.py
Fix https://github.com/kedro-org/kedro-plugins/issues/763
> fix(telemetry): Masking test

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/partitions/partitioned_dataset.py
- kedro-datasets/tests/partitions/test_partitioned_dataset.py
Solves https://github.com/kedro-org/kedro-plugins/issues/769
Implemented `__repr__` for `PartitionedDataset`, so it's aligned with `CachedDataset ` [representation](https://github.com/kedro-org/kedro-plugins/issues/769#issue-2416279032).
Old representation:
New representation:
The current solution includes creating a dummy `dataset` object in order to call `dataset._pretty_repr()`, however only filtered parameters are exposed. The alternative solution is to modify `_pretty_repr()` on the [framework side](https://github.com/kedro-org/kedro/blob/5e1504487d9c5c0d210bc231669f68049c0ca213/kedro/io/core.py#L260), so it's not a class method but a function.
> feat(datasets): Update `__repr__` for `PartitionedDataset`

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Remove notifications when the user opts out of telemetry, according to [this discussion](https://github.com/kedro-org/kedro-plugins/pull/790#discussion_r1697245641).
> feat(telemetry): Remove telemetry opt-out notifications

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/kedro_datasets/pandas/json_dataset.py
As the `_describe` method will be used more often to print dataset (i.e. notebook). We want to make sure credentials are not printed to the terminal. 
From my understanding the `connection` is unique to individual backend and they don't share specific arguments. The only thing that is common is `backend` so I only expose this in the `describe` method.
> fix(datasets): mask credentials in ibis dataset when printed

- kedro-telemetry/kedro_telemetry/plugin.py
Closes #729,
Telemetry will be executed if a CLI command is run outside of a Kedro project (including the `kedro new` command). In this case, the same information will be sent, except for the project-related data.
> feat(telemetry): Run telemetry outside of kedro projects

- kedro-telemetry/README.md
Update the kedro-telemetry README.md following the transition to an opt-out model for telemetry.
> fix(telemetry): Update README.md for opt-out model

- kedro-telemetry/kedro_telemetry/plugin.py
Addresses https://github.com/kedro-org/kedro-plugins/issues/785.
> fix(telemetry): Let environment variables override consent from .telemetry file

- kedro-telemetry/kedro_telemetry/plugin.py
Solves https://github.com/kedro-org/kedro-plugins/issues/781
Changed logging level from `error` to `debug` in case of `OSError` when creating `project_id`.
The error is handled correctly, but logging it pollutes user output as now we print it when every trigger of `before_command_run`. Since the error does not break the execution, it was decided to hide this message from the user. From our side - we can filter those cases by checking that `project_id` is `None` at the heap.
> fix(telemetry): Changed logging level from error to debug to prevent extensive output

- kedro-telemetry/kedro_telemetry/masking.py
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_masking.py
Resolve #794 
* Instead of recursively loading **all the commands** from `KedroCLI` (which are lazy now) to generate a `dict` CLI structure, only load the structure for the command that is called to perform masking.
* I've also updated the test to actually check masking with real Kedro commands since `_mask_kedro_cli` needs the actual `KedroCLI` object.
* Removed the `_recursive_items()` function and associated unit tests since it wasn't being used anywhere.
> fix(telemetry): Avoid eager loading the whole KedroCLI for masking

- kedro-datasets/pyproject.toml
This pull request addresses issue #747.
1. Added `dask-csvdataset`.
2. Removed `polars-genericdataset` as it currently doesn't exist.
3. Added `spark-sparkstreamingdataset`.
4. Restructured the `polars` and `spark` groups for consistency with other groups.
5. Removed `hdfs-base` and `s3fs-base` from `spark-sparkjdbcdataset` as they are not required. They were retained in other groups as they may be necessary depending on the data storage.
6. Updated `Jinja2` to `<3.2.0` for consistency with documentation requirements.
7. Removed the special line for `tables` on Windows, as it was relevant only for Python 3.8 and is no longer necessary.
> fix(datasets): Cleanup of dependency

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Solves https://github.com/kedro-org/kedro-plugins/issues/815
The `identity` parameter is mandatory when sending data to the heap. Not passing it or setting it to `""` or `None` causes the heap server to return `response code 400`.
The problem was that we used `identity=self._user_uuid`. If we failed to read/generate `user_uuid`, it was treated as an empty string, so passing it to `identity` caused `response code 400` when sending data to the server.
To handle the above case `MISSING_USER_IDENTITY` constant was added, which is used as a default value for the `identity` in case `user_uuid` is `""` or `None`.
> fix(telemetry): Set default identity value

- kedro-airflow/kedro_airflow/grouping.py
- kedro-datasets/kedro_datasets_experimental/pytorch/pytorch_dataset.py
Fix https://github.com/kedro-org/kedro-plugins/issues/840
Replace `DataCatalog` with `CatalogProtocol`
> ci(airflow): Replace type hints with CatalogProtocol

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/pandas/gbq_dataset.py
- kedro-datasets/tests/pandas/test_gbq_dataset.py
PR addresses https://github.com/kedro-org/kedro-plugins/issues/825
Adjusted read/write to use `.to_gbq()` and `.read_gbq()` directly from pandas-gbq package (`pd_gbq`) to avoid deprecation warnings
> fix(datasets): Replace deprecated GBQDataset load/save funcs

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/tensorflow/tensorflow_model_dataset.py
This PR resolves the issue in [#839](https://github.com/kedro-org/kedro-plugins/issues/839), where saving `TensorFlowModelDataset` to Azure Blob Storage fails due to incorrect use of `.copy()` from the `fsspec.filesystem` interface.
The issue occurs in the `_save` and `_load` methods on lines 147 and 172, where `.copy()` is used. According to the [fsspec documentation](https://filesystem-spec.readthedocs.io/en/latest/copying.html), `.copy()` is intended for remote-to-remote transfers. Since this involves copying from a local filesystem to remote storage, `.put()` should be used for saving and `.get()` for loading.
The code has been updated to use `.put()` and `.get()` accordingly, replacing the use of `.copy()`. 
Both methods work for local-to-local and local-to-remote(& vice versa) …
> fix(datasets): Use `put()` and `get()` instead of `copy` in `TensorFlowModelDataset`'s `_save` and `_load` methods.

- .pre-commit-config.yaml
top-level `default_stages` uses deprecated stage names (commit) which will be removed in a future version.
run: `pre-commit migrate-config` to automatically fix this.
> chore: replace deprecated `pre-commit` stage names

- kedro-datasets/pyproject.toml
Came across this while trying to run the image classification example on astro airflow. `pillow` only supports python 3.12 from version 10.0 onwards
> chore(datasets): bump `pillow`

- .github/workflows/kedro-airflow.yml
- .github/workflows/kedro-docker.yml
- .github/workflows/kedro-telemetry.yml
- .pre-commit-config.yaml
- kedro-telemetry/README.md
- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/masking.py
- kedro-telemetry/pyproject.toml
- kedro-telemetry/tests/integration/dummy-project/src/dummy_project/__main__.py
- kedro-telemetry/tests/integration/dummy-project/src/dummy_project/pipeline_registry.py
This is in regards to #872, dropping python 3.8 support for kedro-telemetry. Intends to resolve #875.
- removed python 3.8 from github actions matrix
- updated pyproject.toml
- updated python syntax to conform with python 3.9 and above
> chore: remove support for python 3.8 for kedro-telemetry

- .github/workflows/kedro-datasets.yml
- kedro-datasets/CONTRIBUTING.md
- kedro-datasets/README.md
- kedro-datasets/RELEASE.md
- kedro-datasets/docs/source/conf.py
- kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
- kedro-datasets/kedro_datasets/geopandas/geojson_dataset.py
- kedro-datasets/kedro_datasets/matplotlib/matplotlib_writer.py
- kedro-datasets/kedro_datasets/pandas/excel_dataset.py
- kedro-datasets/kedro_datasets/partitions/incremental_dataset.py
- kedro-datasets/kedro_datasets/partitions/partitioned_dataset.py
- kedro-datasets/kedro_datasets/plotly/html_dataset.py
- kedro-datasets/kedro_datasets/plotly/json_dataset.py
- kedro-datasets/kedro_datasets/polars/lazy_polars_dataset.py
- kedro-datasets/kedro_datasets/svmlight/svmlight_dataset.py
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/conftest.py
- kedro-datasets/tests/spark/conftest.py
Hi, this is removing support for python 3.9 and updates the python syntax accordingly. Intended to resolve #818. 
- removed `typing.Union` in favor of `|` operator
- removed `typing.Callable` in favor of `collections.abc.Callable`
- removed python 3.9 from unit test matrix in CI
> chore: remove support for python 3.9

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/ibis/file_dataset.py
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/tests/ibis/test_file_dataset.py
- kedro-datasets/tests/ibis/test_table_dataset.py
https://github.com/kedro-org/kedro-plugins/pull/893#discussion_r1804632435
TODO: Add unit test (make sure connection caching works correctly?)
> fix(datasets): default to DuckDB in in-memory mode

- .github/workflows/check-tsc-vote.yml
I noticed the TSC vote check wasn't triggered on PRs with changes in the core datasets (e.g. https://github.com/kedro-org/kedro-plugins/pull/881). This doesn't need a vote, but the check should run.
> build: fix paths filter for triggering TSC vote check

- kedro-datasets/pyproject.toml
- kedro-datasets/tests/matplotlib/test_matplotlib_writer.py
It's been a while since I tried installing all `kedro-dataset` dependencies and when I did it failed on installing `matplotlib`. I bumped it to the same version as specified here: https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/pyproject.toml#L81 and was then able to install everything.
> build: Bump matplotlib test dependency

- kedro-datasets/pyproject.toml
Temporarily pin `numpy<2` as it's causing issues in builds like:
```
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```
and 
```
==================================== ERRORS ====================================
____________ ERROR collecting kedro_datasets/video/video_dataset.py ____________
kedro_datasets/video/video_dataset.py:15: in <module>
import cv2 …
```
> build(datasets): pin `numpy<2` 

- .github/workflows/no-response.yml
Mirroring https://github.com/kedro-org/kedro/pull/4294 and https://github.com/kedro-org/kedro/pull/4304 on `kedro` to automatically close issues labelled with `support: needs more info` if the author doesn't reply within 28 days or remove the label if the author has responded.
> build: Add wizard GH action to remove label or close info needed issues

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/template/Dockerfile.simple
- kedro-docker/kedro_docker/template/Dockerfile.spark
This PR updates the dependency management for `kedro-docker` to be handled via `uv`.
Fixes https://github.com/kedro-org/kedro-plugins/issues/906
Both template Dockerfiles have been updated to use `uv` for dependency management. The changes have been tested by building a container for an existing Docker project (starter). See the screenshot below:
> feat(docker): Updated Dependency Manager for `kedro-docker` to `uv`

- .github/workflows/kedro-telemetry.yml
- kedro-telemetry/README.md
- kedro-telemetry/RELEASE.md
Related to https://github.com/kedro-org/kedro/issues/4267
* Update CI build to include python 3.13
> build(telemetry): Add official support for python 3.13

- kedro-datasets/pyproject.toml
- kedro-datasets/tests/tensorflow/test_tensorflow_model_dataset.py
> skip tensorfolow for py313

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/tracking/__init__.py
Fixes #954 
This PR is to add the deprecation warning for MetricsTrackingDataset and JSONTrackingDataset as it will be removed soon in the next release
> feat(datasets): add deprecation warning for tracking datatsets

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/_utils/__init__.py
- kedro-datasets/kedro_datasets/_utils/connection_mixin.py
- kedro-datasets/kedro_datasets/ibis/file_dataset.py
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/tests/ibis/test_file_dataset.py
- kedro-datasets/tests/ibis/test_table_dataset.py
Close #935
The `ConnectionMixin` can also be used by something like `pandas.SQLQueryDataset` and `pandas.SQLTableDataset` to share a single connection cache. While this has some value (prevent storing the connections twice, if the user is using both datasets), it's less functionally important as in this specific Ibis case.
> fix(datasets): share the cache of Ibis connections

- kedro-datasets/kedro_datasets/polars/csv_dataset.py
- kedro-datasets/kedro_datasets/polars/eager_polars_dataset.py
- kedro-datasets/kedro_datasets/polars/lazy_polars_dataset.py
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/polars/test_csv_dataset.py
- kedro-datasets/tests/polars/test_eager_polars_dataset.py
Tests are not running with latest Polars
Separated out Polars-related changes from #909. This should merge first.
> fix(datasets): verify file exists if on Polars 1.0

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/pandas/gbq_dataset.py
- kedro-datasets/tests/pandas/test_gbq_dataset.py
Resolve https://kedro.hall.community/using-pandas-with-bigquery-and-parallel-runners-hTdF7LG3995h#a921cd9d-aa25-4752-9307-1862590a833d by delaying `bigquery.Client()` creation, as done in similar datasets.
Also, as it stands now, the `GBQQueryDataset` doesn't need a `bigquery.Client()`? I think it would make sense to potentially implement `GBQQueryDataset.exists()` (`if not query_or_table._is_query()`, checked with something like https://github.com/googleapis/python-bigquery-pandas/blob/78aa01e3f039500c9fabbcdd8d8dcfa3e5c42b73/pandas_gbq/gbq.py#L71), but I haven't done that in this PR. (You'd need to figure out what to do if it isn't a table; would you return `True` but raise a warning?)
> fix(datasets): make `GBQTableDataset` serializable

- kedro-datasets/docs/source/conf.py
Related https://github.com/kedro-org/kedro/issues/4174
Related PR https://github.com/kedro-org/kedro/pull/4410
Docs build for this PR - https://kedro--985.org.readthedocs.build/projects/kedro-datasets/en/985/
Please check by going to API docs and clicking on "[source]"
> docs(datasets): Move to linkcode extension

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/ibis/file_dataset.py
Ibis 10.0 made a lot of arguments keyword-only, including `table_name` for `read_*` method.
This fixes the `ibis.FileDataset` doctest.
This doesn't fix the PyArrow issue, which I've separated into #1006. Would appreciate if these can be merged separately (despite CI failure) to maintain a cleaner commit history (for when the PyArrow pin should be reverted).
> fix(datasets): use kwarg for Ibis `read_*` methods

- kedro-datasets/pyproject.toml
PyArrow 19.0.0 broke stuff.
This fixes the doctest broken by PyArrow 19.0.0, but not the one broken by Ibis 10.0 (fixed in #1005). Would appreciate if these can be merged separately, so that there's a clearer commit history + we can easily rever the PyArrow pin.
> build(datasets): pin PyArrow until `19.0.1` is out

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/snowflake/snowpark_dataset.py
Solves issues reported in https://github.com/kedro-org/kedro-plugins/issues/972 and http://github.com/kedro-org/kedro-plugins/issues/1034
The check for none was added by me in https://github.com/kedro-org/kedro-plugins/pull/881 to fix lint complaints. However, on looking at it again now I realised the `session` property wasn't actually used, so updated the code to use that instead of having the None check.
> fix(datasets): Session handling for `SnowParkDataset`

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Solves https://github.com/kedro-org/kedro/issues/4620
Since we decided to keep the old catalog name - `DataCatalog` (https://github.com/kedro-org/kedro/issues/4721) -importing it for both versions will not cause the issue. However, we use the old list API to list datasets, which was deprecated for the new catalog. In this PR, we replace the old API call (list) with the new one (keys) and fallback to the old one in case the new one is not found.
> feat(telemetry): Update telemetry to support both catalogs

- .secrets.baseline
- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/partitions/incremental_dataset.py
- kedro-datasets/kedro_datasets/partitions/partitioned_dataset.py
- kedro-datasets/tests/partitions/test_incremental_dataset.py
- kedro-datasets/tests/partitions/test_partitioned_dataset.py
- kedro-datasets/tests/spark/test_deltatable_dataset.py
- kedro-datasets/tests/spark/test_spark_dataset.py
Fix https://github.com/kedro-org/kedro-plugins/issues/1107 and address https://github.com/kedro-org/kedro-plugins/issues/1080
- Updated references to `modular_pipelines` 
- Updated import for `CREDENTIALS_KEYS`
- Use `SharedMemoryCatalog` for paralllel running
> chore(datasets): Make `kedro-datasets` compatible with 1.0.0
