kedro-org/kedro-plugins

- Makefile
Signed-off-by: lorenabalan <lorena.balan@quantumblack.com>
Update make instructions to make plugin release easier.
> Modify Makefile per plugin

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
Signed-off-by: lorenabalan <lorena.balan@quantumblack.com>
Release new version of `kedro-telemetry`.
> Bump up version of kedro-telemetry to 0.1.4

- .circleci/continue_config.yml
- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
- kedro-telemetry/requirements.txt
- kedro-telemetry/setup.py
- kedro-telemetry/test_requirements.txt
- kedro-telemetry/tests/test_masking.py
Release `kedro-telemetry` version `0.2.0`
> Release `kedro-telemetry`

- kedro-telemetry/README.md
Signed-off-by: Ahdra Merali <ahdra.merali@quantumblack.com>
Adds changes outlined in #23
> Update the README.md to point to LF AI & Data

- README.md
Since migrating to kedro-plugins the README looks very empty. This PR adds some brief descriptions of the plugins to the README.
Update README with brief plugin descriptions
> Enhance the kedro-plugins README with plugin descriptions

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
> `kedro-telemetry` 0.2.1 release

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
> Release kedro-telemetry 0.2.2

- kedro-telemetry/features/steps/dummy.feature
Signed-off-by: Ahdra Merali <ahdra.merali@quantumblack.com>
kedro-telemetry was missing a feature file, causing the package build to fail. Solution follows kedro-datasets setup; see #43 for more.
Added dummy feature file to kedro-telemetry to allow `make e2e-tests` to pass. Running `behave` from kedro-telemetry now concludes without error.
To test:
```
>  cd path/to/kedro-plugins/kedro-telemetry
>  behave
```
Desired output:
```
0 features passed, 0 failed, 0 skipped
0 scenarios passed, 0 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
```
> Fix telemetry release CI

- .circleci/continue_config.yml
- kedro-telemetry/features/steps/dummy.feature
- kedro-telemetry/test_requirements.txt
> Add missing behave requirement

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/__init__.py
Release version 0.5.1 of kedro-airflow.
> Release Kedro-Airflow 0.5.1

- kedro-datasets/kedro_datasets/__init__.py
- kedro-datasets/setup.py
- kedro-datasets/test_requirements.txt
Release to align with kedro so doc tests can pass on it.
> Release kedro-datasets 0.0.6

- kedro-datasets/kedro_datasets/__init__.py
Signed-off-by: Ankita Katiyar <ankitakatiyar2401@gmail.com>
Minor release before `Kedro 0.18.4`
> Release `kedro-datasets 0.0.7`

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/__init__.py
Release kedro-docker 0.3.1 with the improvements made in #92.
No changes to the API; a patch version is warranted.
> Release Kedro-Docker 0.3.1

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release 1.1.0 which includes new datasets
> Release `kedro-datasets` version `1.1.0`

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release version 1.1.1 which prevents warnings when building the Kedro documentation on Read the Docs.
> Release `kedro-datasets` version `1.1.1`

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release datasets version 1.2.0
> Release `kedro-datasets` version `1.2.0`

- kedro-datasets/setup.py
- kedro-datasets/test_requirements.txt
> Fix tensorflow requirements for ARM Macs

- kedro-datasets/kedro_datasets/spark/spark_dataset.py
- kedro-datasets/setup.py
https://kedro-org.slack.com/archives/C03RKP2LW64/p1679955432199279
* Add `snowflake` extra
* Change `snowpark_require` to `snowflake_require` for consistency
* Change `tensorflow_required` to `tensorflow_require` for consistency
* Alphabetize stuff
* Fix a listing error introduced by a previous PR
> build(datasets): add the missing `snowflake` extra

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
> Fix telemetry bug - add checking for project statistics

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
> Kedro-Telemetry release 0.2.4

- kedro-datasets/setup.py
Polars is releasing and breaking code very fast, and it's desirable that we at least aim to be compatible with the latest `0.x` version.
Cherry-picked from gh-170 in case we can merge this one faster.
> Upgrade Polars

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/README.md
> docs: Add community contributions

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/api/api_dataset.py
- kedro-datasets/setup.py
https://github.com/kedro-org/kedro/pull/2485#issuecomment-1559120329
> docs: Fix APIDataSet docstring

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
doc fix release together with kedro 0.18.9 https://github.com/kedro-org/kedro/pull/2619
* Added `SparkStreamingDataSet`
> build(datasets): release 1.4.0

- .github/ISSUE_TEMPLATE/config.yml
See https://github.com/kedro-org/kedro-devrel/issues/40
> chore: Direct users to awesome-kedro for community content

- kedro-airflow/README.md
- kedro-airflow/kedro_airflow/airflow_dag_template.j2
Removed unused imports in `kedro-airflow` template
> refactor: remove unused imports

- kedro-datasets/RELEASE.md
- kedro-datasets/setup.py
The setup.py missed the `pickle` extras installation.
> fix(datasets): Fix missing pickle setup in `kedro-datasets`

- .github/workflows/validate-pr-title.yaml
Resolve permission issues happening due to this action
WIP feature for this action requires "write" permission for pull requests. Removing this
> ci: Remove wip feature from Lint PR action

- kedro-datasets/kedro_datasets/tensorflow/README.md
> docs(datasets): fix typo in Markdown

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
> chore(datasets): kedro-datasets 1.4.2

- kedro-airflow/pyproject.toml
Closes: https://github.com/kedro-org/kedro-plugins/issues/269
> chore(airflow): relax `semver` requirement bound

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release `kedro-datasets` 1.5.0
> build(datasets): Release 1.5.0

- kedro-telemetry/pyproject.toml
Add open-bound to kedro-telemetry
> chore: Make kedro-telemetry open-bound

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
- kedro-telemetry/pyproject.toml
> build(telemetry): Release 0.2.5

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
> build(datasets): Release `1.7.1`

- CONTRIBUTING.md
- Makefile
- kedro-airflow/CONTRIBUTING.md
- kedro-datasets/CONTRIBUTING.md
> docs: Update CONTRIBUTING.md and add one for `kedro-datasets`

- kedro-datasets/.readthedocs.yaml
- kedro-datasets/pyproject.toml
Signed-off-by: Nok <nok.lam.chan@quantumblack.com>
Same fix from `kedro` to fix the RTD build issue. See: https://github.com/kedro-org/kedro/pull/3182
> chore: Hot fix for RTD due to bad pip version

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/__init__.py
> build(airflow): Release 0.7.0

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
Release `kedro-telemetry` 0.3.0
> build(telemetry): Release 0.3.0

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/__init__.py
> build(docker): Release 0.4.0

- kedro-airflow/README.md
> style(airflow): blacken README.md of Kedro-Airflow

- kedro-datasets/docs/source/conf.py
Same as https://github.com/kedro-org/kedro/pull/3192/commits/f484fecfb6a0aa83a436e8b382c1ad775501e30c, see https://github.com/kedro-org/kedro/issues/3193
> fix(datasets): Fix missing jQuery

- kedro-datasets/kedro_datasets/polars/lazy_polars_dataset.py
> fix(datasets): Fix Lazy Polars dataset to use the new-style base class

- kedro-datasets/kedro_datasets/partitions/__init__.py
> chore(datasets):  lazily load `partitions` classes

- kedro-datasets/docs/source/conf.py
- kedro-datasets/docs/source/kedro_datasets.rst
- kedro-datasets/kedro_datasets/huggingface/__init__.py
- kedro-datasets/kedro_datasets/huggingface/hugging_face_dataset.py
- kedro-datasets/kedro_datasets/huggingface/transformer_pipeline_dataset.py
- kedro-datasets/setup.py
- kedro-datasets/tests/huggingface/conftest.py
- kedro-datasets/tests/huggingface/test_hugging_face_dataset.py
- kedro-datasets/tests/huggingface/test_transformer_pipeline_dataset.py
As per title 🤗 
cc @dannyrfar @kevin-koga-mckinsey @matescharnitzky @tomershor @pymousse @belavaishali @khangjrakpamarjun
This is still missing tests and docstrings. Ready for review code-wise.
> feat(datasets): Add Hugging Face datasets

- Makefile
- kedro-datasets/kedro_datasets/api/api_dataset.py
> test(datasets): make `api.APIDataset` doctests run

- Makefile
- kedro-datasets/kedro_datasets/matplotlib/matplotlib_writer.py
Should pass given kedro-org/kedro#3345.
> test(datasets): add outputs to matplotlib doctests

- .github/workflows/kedro-datasets.yml
Better practice, avoid potential issues of overwriting installed dependencies
> ci(datasets): install deps in single `pip install`

- kedro-datasets/docs/source/kedro_datasets.rst
> docs(datasets): Document `IncrementalDataset`

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Breaking release for `kedro-datasets`
Includes removal of `DataSet` naming.
> build(datasets): Release `2.0.0` 

- kedro-telemetry/pyproject.toml
Fix https://github.com/kedro-org/kedro-plugins/issues/470
> ci(telemetry): Pin `PyYAML`

- kedro-datasets/kedro_datasets/geopandas/README.md
- kedro-datasets/kedro_datasets/tensorflow/README.md
- kedro-datasets/tests/polars/test_lazy_polars_dataset.py
- kedro-datasets/tests/redis/test_redis_dataset.py
- kedro-datasets/tests/spark/test_spark_dataset.py
> chore(datasets): replace more "data_set" instances

- Makefile
- kedro-datasets/kedro_datasets/databricks/managed_table_dataset.py
- kedro-datasets/kedro_datasets/pandas/deltatable_dataset.py
- kedro-datasets/kedro_datasets/pandas/gbq_dataset.py
- kedro-datasets/kedro_datasets/partitions/incremental_dataset.py
- kedro-datasets/kedro_datasets/polars/lazy_polars_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_jdbc_dataset.py
- kedro-datasets/kedro_datasets/tensorflow/tensorflow_model_dataset.py
Part of https://github.com/kedro-org/kedro/issues/2287
Fixed doctests for:
1. `kedro_datasets/pandas/deltatable_dataset.py`
2. `kedro_datasets/polars/lazy_polars_dataset.py`
3. `kedro_datasets/polars/lazy_polars_dataset.py`
> chore(datasets): Fix doctests

- kedro-telemetry/tests/test_masking.py
- kedro-telemetry/tests/test_plugin.py
Fix telemetry metadata to resolve failed night builds
> fix: telemetry metadata

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/plugin.py
- kedro-airflow/tests/test_plugin.py
Closes https://github.com/kedro-org/kedro-plugins/issues/487
> feat(airflow): include environment name in DAG filename

- kedro-datasets/docs/source/_templates/layout.html
Enable search-as-you type on Kedro-viz docs. Also opens the search when you click on Ctrl+K
Basically copy/pasted the same javascript code from Kedro docs.
> feat(datasets): Enable search-as-you type on Kedro-datasets docs

- kedro-telemetry/README.md
I reviewed the `kedro-telemetry` data collection process to update the documentation. 
I found no evidence that we collect the host name and project name, so I removed those from the documentation. 
I have included information about the tools and the number of datasets, nodes, and pipelines we collect. 
Additionally, I have added the hashed username to the table to clarify its collection.
> docs: Update kedro-telemetry docs on which data is collected

- kedro-telemetry/README.md
https://github.com/kedro-org/kedro-plugins/issues/508, https://github.com/kedro-org/kedro/pull/3603
> docs(telemetry): Direct readers to Kedro documentation for further information on telemetry

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
This PR addresses the following issues: 
1. It removes parameters from dataset counts, 
2. ensures proper collection of tools by converting them to strings,
3. includes an example_pipeline in the data collection process.
> fix: telemetry data and add example_pipeline

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/plugin.py
Fix #380.
Sort the dependencies dictionaries to make sure it's deterministic.
> feat(airflow): make sure `kedro airflow create` is deterministic

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release `kedro-datasets` 2.1.0
> build(datasets): Release `kedro-datasets` 2.1.0

- kedro-datasets/.readthedocs.yaml
- kedro-datasets/kedro_datasets/huggingface/transformer_pipeline_dataset.py
- kedro-datasets/kedro_datasets/tensorflow/tensorflow_model_dataset.py
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/tensorflow/test_tensorflow_model_dataset.py
> fix(datasets): Various fixes

- kedro-docker/kedro_docker/helpers.py
- kedro-docker/kedro_docker/plugin.py
Fixing issues flagged by `mypy` in `kedro-docker`. See https://github.com/kedro-org/kedro-plugins/actions/runs/8616081473/job/23612944257?pr=638 the list of issues flagged by `mypy`.
Will merge this into #638 before `main`.
> chore: Fix `mypy` issues on `kedro-docker`

- kedro-datasets/RELEASE.md
- kedro-datasets/pyproject.toml
> fix(datasets): Restore support for pandas 1 and PySpark 2

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Release `kedro-datasets 3.0.0`
> feat: Release kedro-datasets version 3.0.0

- kedro-datasets/experimental/README.md
Closes #578 
I will add links to the documentation on experimental & regular datasets when they're completed in #579
> docs: Add `experimental` directory

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/__init__.py
> build(docker): Release 0.6.0

- kedro-docker/features/environment.py
- kedro-docker/kedro_docker/template/Dockerfile.simple
- kedro-docker/kedro_docker/template/Dockerfile.spark
Fix https://github.com/kedro-org/kedro-plugins/issues/674
> build(docker): Unpin pip for `kedro-docker`

- kedro-datasets/.readthedocs.yaml
- kedro-datasets/docs/source/api/kedro_datasets_experimental.rst
- kedro-datasets/docs/source/conf.py
- kedro-datasets/docs/source/index.md
- kedro-datasets/pyproject.toml
Closes #682 
Added API docs configuration for the experimental datasets, making sure any experimental dependencies are installed in the docs building process.
> docs(datasets): Add setup for building API docs for experimental datasets

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/__init__.py
> build(airflow): Release 0.9.0 

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
> build(datasets): Release kedro-datasets 3.0.1

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
> build(telemetry): Release 0.5.0

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
> build(datasets): 4.0.0

- kedro-airflow/RELEASE.md
- kedro-airflow/kedro_airflow/__init__.py
Release 0.9.1 🚀
Closes https://github.com/kedro-org/kedro-plugins/issues/776
> build(airflow): Release 0.9.1

- kedro-datasets/pyproject.toml
Solves https://github.com/kedro-org/kedro-plugins/issues/746
> fix(datasets): Add missing imports to `databricks-managedtabledataset`

- kedro-datasets/tests/pandas/test_deltatable_dataset.py
Fix #783 
`deltalake` had a new release last week - https://pypi.org/project/deltalake/#history
> ci: Fix `pandas.DeltaTableDataset` tests

- kedro-telemetry/kedro_telemetry/__init__.py
- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/tests/test_plugin.py
Resolve #819 
Made most logging messages `DEBUG` as users can't do much about them.
> chore(telemetry): Change logging level to `DEBUG` for most messages

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/__init__.py
> feat: Release kedro-docker 0.6.1

- kedro-datasets/RELEASE.md
- kedro-datasets/pyproject.toml
> fix(datasets): fix incorrect `pandas` optional dependency

- kedro-datasets/pyproject.toml
The bounds are overly strict, so much so that they don't reflect what's in the `test` dependencies.
Discovered the problem because I ran into resolution problems while trying to set up a pixi environment.
I also cleaned up some inconsistent trailing commas.
> build(datasets): relax bounds for holoviews, scipy

- .github/PULL_REQUEST_TEMPLATE.md
Added a checkbox to the PR form to remind creators that core dataset contributions need a TSC vote.
> chore: Update PR template with checkbox for core dataset contribution

- kedro-datasets/CONTRIBUTING.md
- kedro-datasets/README.md
- kedro-datasets/kedro_datasets/ibis/file_dataset.py
- kedro-datasets/kedro_datasets/ibis/table_dataset.py
- kedro-datasets/kedro_datasets/spark/spark_streaming_dataset.py
Fix #889 which is happening due to `mypy` new release
The docs link check was also failing, I tried changing it to https://opensource.org/license/apache-2-0 but that didn't work so I linked it to our own `LICENSE.md` since that's what we do on Kedro's core repo as well.
> ci(datasets): Fix mypy errors

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Create a release containing `ibis.FileDataset`.
The TSC vote was missed for `ibis.FileDataset`; therefore, this PR will also serve as the TSC vote. If `ibis.FileDataset` fails the vote, I will close this and create a separate PR to remove it.
> build(datasets): make Kedro-Datasets 5.1.0 release

- kedro-airflow/RELEASE.md
- kedro-docker/RELEASE.md
- kedro-telemetry/RELEASE.md
I noticed the headers in the release notes were incorrectly mentioning versions that haven't been released yet, so reverted those to "Upcoming Release"
> style: Cleanup release notes with correct headers

- .github/workflows/kedro-docker.yml
- kedro-docker/README.md
- kedro-docker/RELEASE.md
- kedro-docker/features/environment.py
Related to https://github.com/kedro-org/kedro/issues/4267
* Update CI build to include python 3.13
> build(docker): Add official support for python 3.13

- kedro-telemetry/RELEASE.md
- kedro-telemetry/kedro_telemetry/__init__.py
Resolves #945 
* Update kedro-telemetry init file
* Update Release note
> build(telemetry): Release 0.6.2

- kedro-docker/RELEASE.md
- kedro-docker/kedro_docker/__init__.py
Resolves #944 
**NOTE:** This PR should be merged after https://github.com/kedro-org/kedro-plugins/pull/937
* Update kedro-docker init file
* Update Release note
> build(docker): Release 0.6.2

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
Resolves #942 
* Update Release note
* Update `init` file version of kedro_datasets to 6.0.0
> build(datasets): Release 6.0.0

- kedro-datasets/pyproject.toml
> chore(datasets): pin Polars to avoid build failure

- kedro-datasets/kedro_datasets/pandas/csv_dataset.py
Resolves [#4585](https://github.com/kedro-org/kedro/issues/4585)
* Updated example docstring
> chore(datasets): Update csv usage example to include append mode

- .secrets.baseline
- kedro-datasets/tests/partitions/test_partitioned_dataset.py
Modify dataset test error messages to align with updates introduced in https://github.com/kedro-org/kedro/pull/4580.
> fix(datasets): Modify test error messages with changes from PR #4580

- kedro-datasets/pyproject.toml
Polars 1.26.0 got released
Testing in CI
> revert(datasets): unpin Polars given bug was fixed

- kedro-datasets/CONTRIBUTING.md
- kedro-datasets/kedro_datasets/conftest.py
- kedro-datasets/kedro_datasets/huggingface/hugging_face_dataset.py
- kedro-datasets/kedro_datasets/matplotlib/matplotlib_dataset.py
- kedro-datasets/kedro_datasets/pandas/sql_dataset.py
- kedro-datasets/kedro_datasets/pillow/image_dataset.py
- kedro-datasets/kedro_datasets/polars/csv_dataset.py
> chore: Remove mentions of doctest since it doesn't work with mkdocs format

- kedro-datasets/kedro_datasets/huggingface/hugging_face_dataset.py
> fix(datasets): Fix HFDataset to extend to AbstractDataset instead of AbstractVersionedDataset

- kedro-datasets/mkdocs.yml
Since we now have a separate link for the docs RC, this PR is to point to the right version rather than the develop
> docs: update kedro doc to 1.0.0rc1

- kedro-telemetry/tests/test_masking.py
After this change https://github.com/kedro-org/kedro/pull/4940, tests for telemetry should be updated correspondingly.
> test(telemetry): Fix unit tests after catalog CLI command renaming

- kedro-datasets/RELEASE.md
- kedro-datasets/docs/api/kedro_datasets/matplotlib.MatplotlibWriter.md
- kedro-datasets/docs/index.md
- kedro-datasets/kedro_datasets/matplotlib/__init__.py
- kedro-datasets/kedro_datasets/matplotlib/matplotlib_writer.py
- kedro-datasets/mkdocs.yml
- kedro-datasets/pyproject.toml
- kedro-datasets/tests/matplotlib/test_matplotlib_dataset.py
Context in https://github.com/kedro-org/kedro-starters/issues/286#issuecomment-3061749512
> chore(datasets): Revert removal of MatplotlibWriter

- kedro-datasets/RELEASE.md
- kedro-datasets/kedro_datasets/__init__.py
- kedro-datasets/pyproject.toml
> build(datasets): Release 8.0.0

- kedro-telemetry/kedro_telemetry/plugin.py
- kedro-telemetry/pyproject.toml
- kedro-telemetry/tests/test_plugin.py
Companion to kedro-org/kedro#5043
> chore(telemetry): use tomllib (or tomli) over toml

- kedro-datasets/docs/overrides/partials/copyright-legal-socials.html
Update copyright notice from “QuantumBlack, AI by McKinsey” to “LF AI & Data Foundation”, and removed T&C
> docs: update copy right and remove T&C
